[package]
name = "4k-converter"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.16"
toml = "0.9.5"
serde = "1.0.219"

mc-classic-js = "0.2.4"
mc-classic = "0.1.2"
rusqlite = "0.37.0"
serde_json = "1.0.143"

